apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: adp-portal
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    github.com/project-slug: defra-adp-sandpit/adp-portal
    backstage.io/techdocs-ref: url:https://dev.azure.com/defragovuk/DEFRA-FFC/_git/DEFRA-FFC.wiki
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
