# Name: Defra - Backstage
appId: ${GITHUB_APP_ID}
webhookUrl: https://smee.io/
clientId: ${GITHUB_CLIENT_ID}
clientSecret: ${GITHUB_CLIENT_SECRET}
webhookSecret: ThisIsRequiredButNotUsed
privateKey: ${GITHUB_PRIVATE_KEY}

